title       : "lifehacker 101 Android corner"
repo        : "lifehacker-101/ota"
color       : "#e9837f"
image       : "https://avatars.githubusercontent.com/u/105009381?s=200&v=4"

sass:
  sass_dir: _sass

include:
  - _headers

exclude:
  - Gemfile*
  - vendor
  - gen_mirror_json.py
  - gen_pages.py
  - LICENSE*

defaults:
  - scope:
      path: "**/*.md"
    values:
      layout: app

collections:
  device:
    output: true
