# theme       : jekyll-theme-slate
title       : "LineageOS Unofficial Builds"
repo        : "lifehackerhansol-android/ota"
color       : "#e9837f"
image       : "https://avatars.githubusercontent.com/u/46971470?s=400&u=8e42e29aa9df11e990436648b66906c16b3f0ed7&v=4"

sass:
  sass_dir: _sass

exclude:
  - Gemfile*
  - vendor
  - gen_mirror_json.py
  - gen_pages.py
  - LICENSE*

defaults:
  - scope:
      path: "**/*.md"
    values:
      layout: app

collections:
  device:
    output: true
